In [2]:
# Must be included at the beginning of each new notebook. Remember to change the app name.
import findspark
findspark.init('/home/ubuntu/spark-2.1.1-bin-hadoop2.7')
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('missing').getOrCreate()

In [3]:
# Importing data which has a header. Schema is automatically configured.
df = spark.read.csv('rebalanced_dataset.csv', header=True, inferSchema=True)
df_uc = spark.read.csv('rebalanced_dataset_dirty.csv', header=True, inferSchema=True)
df_h1 = spark.read.csv('rebalanced_dataset_half1.csv', header=True, inferSchema=True)
df_h2 = spark.read.csv('rebalanced_dataset_half2.csv', header=True, inferSchema=True)

In [4]:
# Show number of columns and rows
print((df.count(), len(df.columns)))

(984, 32)

In [5]:
# Show the columns contained in the dataset
print(df.columns)

['_c0', 'Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class']

In [6]:
# Show the data type of each column
df.dtypes

[('_c0', 'int'),
 ('Time', 'int'),
 ('V1', 'double'),
 ('V2', 'double'),
 ('V3', 'double'),
 ('V4', 'double'),
 ('V5', 'double'),
 ('V6', 'double'),
 ('V7', 'double'),
 ('V8', 'double'),
 ('V9', 'double'),
 ('V10', 'double'),
 ('V11', 'double'),
 ('V12', 'double'),
 ('V13', 'double'),
 ('V14', 'double'),
 ('V15', 'double'),
 ('V16', 'double'),
 ('V17', 'double'),
 ('V18', 'double'),
 ('V19', 'double'),
 ('V20', 'double'),
 ('V21', 'double'),
 ('V22', 'double'),
 ('V23', 'double'),
 ('V24', 'double'),
 ('V25', 'double'),
 ('V26', 'double'),
 ('V27', 'double'),
 ('V28', 'double'),
 ('Amount', 'double'),
 ('Class', 'int')]

In [7]:
# Get summary statistics
df.select('Time','V1', 'V2', 'V3', 'V4').describe().show()
df.select('V5','V6', 'V7', 'V8', 'V9').describe().show()
df.select('V10','V11', 'V12', 'V13', 'V14').describe().show()
df.select('V15','V16', 'V17', 'V18', 'V19').describe().show()
df.select('V20','V21', 'V22', 'V23', 'V24').describe().show()
df.select('V25','V26', 'V27', 'V28', 'Amount').describe().show()
df.select('Class').describe().show()

+-------+-----------------+-------------------+-----------------+-------------------+------------------+
|summary|             Time|                 V1|               V2|                 V3|                V4|
+-------+-----------------+-------------------+-----------------+-------------------+------------------+
|  count|              984|                984|              984|                984|               984|
|   mean| 88299.5325203252|-2.3261755370132096|1.811482649214429|-3.5201620340619932|2.3300934150193044|
| stddev|48878.96431277863|  5.529796067601339|3.697605750483812|  6.213435530803077|3.1748910196942064|
|    min|              187|       -30.55238004|     -16.46099886|       -31.10368482|      -3.503648015|
|    max|           172069|        2.323150188|      22.05772899|        3.275071757|       12.11467184|
+-------+-----------------+-------------------+-----------------+-------------------+------------------+

+-------+-------------------+-------------------+------------------+------------------+-------------------+
|summary|                 V5|                 V6|                V7|                V8|                 V9|
+-------+-------------------+-------------------+------------------+------------------+-------------------+
|  count|                984|                984|               984|               984|                984|
|   mean|-1.5853699220030455|-0.6736555584136189|-2.777005807891258|0.2680496113048781|-1.2737092653892277|
| stddev|  4.190858683527686| 1.7449637546354555| 5.859627036045515| 4.869259192948764| 2.3297480360755443|
|    min|       -22.10553152|       -6.406266634|      -43.55724157|      -41.04426092|       -13.43406632|
|    max|         11.0950886|         7.71757738|       9.179305398|       20.00720837|        4.563045558|
+-------+-------------------+-------------------+------------------+------------------+-------------------+

+-------+-------------------+------------------+------------------+--------------------+-------------------+
|summary|                V10|               V11|               V12|                 V13|                V14|
+-------+-------------------+------------------+------------------+--------------------+-------------------+
|  count|                984|               984|               984|                 984|                984|
|   mean|-2.8085182028374005|1.9236523938689023|-3.109208644495933|-0.05614496125000006|-3.4754888529105656|
| stddev|  4.558187854883452|2.7580833601157755|4.6046458513521005|  1.0594460950490578|  4.661092835106606|
|    min|       -24.58826244|      -2.614950895|      -18.68371463|        -3.248010499|       -19.21432549|
|    max|         7.50473042|       12.01891318|       2.163905473|         3.133483207|        3.442421996|
+-------+-------------------+------------------+------------------+--------------------+-------------------+

+-------+--------------------+-------------------+-------------------+-------------------+------------------+
|summary|                 V15|                V16|                V17|                V18|               V19|
+-------+--------------------+-------------------+-------------------+-------------------+------------------+
|  count|                 984|                984|                984|                984|               984|
|   mean|-0.04030501017682926|-2.0615916511788623|-3.3355073497774383|-1.1249889078739836|0.3566594984725614|
| stddev|  0.9538369299502114|  3.484201217756755|  5.967709644562135| 2.3968584909763155|1.2924920667912638|
|    min|        -4.498944677|       -14.12985452|       -25.16279937|       -9.498745921|      -4.676092279|
|    max|         2.471357904|        3.139655659|        6.739384385|        3.790316212|        5.22834179|
+-------+--------------------+-------------------+-------------------+-------------------+------------------+

+-------+------------------+-------------------+--------------------+--------------------+--------------------+
|summary|               V20|                V21|                 V22|                 V23|                 V24|
+-------+------------------+-------------------+--------------------+--------------------+--------------------+
|  count|               984|                984|                 984|                 984|                 984|
|   mean|0.1894717091849595|0.34123218185365806|0.011701276962398538|-0.03791452343191053|-0.05436679801829267|
| stddev|1.1478300066705491| 2.7890870399186336|  1.1664116189294753|  1.2231978006458168|  0.5641050243618679|
|    min|      -7.756787449|       -22.79760391|        -8.887017141|        -19.25432762|        -2.028024229|
|    max|       11.05900429|        27.20283916|         8.361985192|         6.139975012|          1.64407629|
+-------+------------------+-------------------+--------------------+--------------------+--------------------+

+-------+--------------------+--------------------+-------------------+--------------------+------------------+
|summary|                 V25|                 V26|                V27|                 V28|            Amount|
+-------+--------------------+--------------------+-------------------+--------------------+------------------+
|  count|                 984|                 984|                984|                 984|               984|
|   mean|0.029637263869918676|0.018566925676829243|0.07733819283028448|0.027833886111788612|105.87366869918677|
| stddev|  0.6712962116001703|  0.4804794057111987|  1.021201802817132|  0.4376038535619511| 283.5358585873014|
|    min|        -4.781605522|        -1.263599611|       -7.263482146|        -4.555242788|               0.0|
|    max|         2.208209178|         2.745260672|        3.800539534|         1.779363852|           5026.26|
+-------+--------------------+--------------------+-------------------+--------------------+------------------+

+-------+------------------+
|summary|             Class|
+-------+------------------+
|  count|               984|
|   mean|               0.5|
| stddev|0.5002542588519274|
|    min|                 0|
|    max|                 1|
+-------+------------------+

In [8]:
from pyspark.sql.functions import isnan, when, count, col

a = ['Time','V1', 'V2', 'V3', 'V4', 'V5','V6', 'V7', 'V8', 'V9', 'V10','V11', 'V12', 'V13', 'V14', 'V15','V16', 'V17', 'V18', 'V19']
b = ['V20','V21', 'V22', 'V23', 'V24', 'V25','V26', 'V27', 'V28', 'Amount', 'Class']

df_uc.select([count(when(isnan(c) | col(c).isNull(), c)).alias(c) for c in a]).show()
df_uc.select([count(when(isnan(c) | col(c).isNull(), c)).alias(c) for c in b]).show()

+----+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|Time| V1| V2| V3| V4| V5| V6| V7| V8| V9|V10|V11|V12|V13|V14|V15|V16|V17|V18|V19|
+----+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|   1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
+----+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+

+---+---+---+---+---+---+---+---+---+------+-----+
|V20|V21|V22|V23|V24|V25|V26|V27|V28|Amount|Class|
+---+---+---+---+---+---+---+---+---+------+-----+
|  0|  0|  0|  0|  0|  0|  0|  0|  0|     0|    0|
+---+---+---+---+---+---+---+---+---+------+-----+

In [9]:
df_uc.select("Class").distinct().show()

+-----+
|Class|
+-----+
|    0|
| Zero|
|    1|
+-----+

In [10]:
from pyspark.sql.functions import *

clean_df = df_uc.withColumn('Class', regexp_replace('Class', 'Zero', '0'))
clean_df.select("Class").distinct().show()

+-----+
|Class|
+-----+
|    0|
|    1|
+-----+

In [11]:
df_stand = df.select('Time','Amount')
df_stand.show()

+------+------+
|  Time|Amount|
+------+------+
|129707| 76.87|
|146022|  1.18|
| 58762|  11.5|
| 40276|   1.0|
|143438|   8.9|
| 63470|100.92|
|134766|   1.0|
| 93856|209.65|
| 68899| 198.0|
| 67250| 10.96|
|  8886|   1.0|
|171483|  3.69|
| 76394| 46.86|
| 80524|  5.49|
| 55279|   1.0|
| 25198| 99.99|
| 91524|   1.0|
|120591| 45.58|
|161929|  2.28|
|129186|  7.18|
+------+------+
only showing top 20 rows

## Normalisation/standardisation

In [12]:
from pyspark.sql.functions import col, mean, stddev
from pyspark.sql import Window

input_col = "Time"
output_col = "Time_scaled"

w = Window.partitionBy()

mu = mean(input_col).over(w)
sigma = stddev(input_col).over(w)

df_sc = df.withColumn(output_col, (col(input_col) - mu)/(sigma))

In [13]:
df_sc.select("Time_scaled").show()

+--------------------+
|         Time_scaled|
+--------------------+
|  0.8471428980104121|
|  1.1809265660848745|
| -0.6042994759732067|
| -0.9824989787635539|
|  1.1280612888366728|
| -0.5079799228445172|
|  0.9506434543566398|
| 0.11367809358886415|
| -0.3969096480068674|
|-0.43064604204025925|
|  -1.624697528616902|
|  1.7018254917878404|
|-0.24357170180900675|
|-0.15907727648583606|
| -0.6755571232857015|
|  -1.290975236638316|
| 0.06596840839427963|
|  0.6606414013406726|
|  1.5063630851201473|
|  0.8364839160265448|
+--------------------+
only showing top 20 rows

## Creation of a new variable

In [14]:
from pyspark.sql import functions as f
df_withcol = df.withColumn('LargeTransaction', f.when(f.col('Amount') > 150, "Yes").otherwise("No"))
df_withcol.select("LargeTransaction", "Amount").show()

+----------------+------+
|LargeTransaction|Amount|
+----------------+------+
|              No| 76.87|
|              No|  1.18|
|              No|  11.5|
|              No|   1.0|
|              No|   8.9|
|              No|100.92|
|              No|   1.0|
|             Yes|209.65|
|             Yes| 198.0|
|              No| 10.96|
|              No|   1.0|
|              No|  3.69|
|              No| 46.86|
|              No|  5.49|
|              No|   1.0|
|              No| 99.99|
|              No|   1.0|
|              No| 45.58|
|              No|  2.28|
|              No|  7.18|
+----------------+------+
only showing top 20 rows

## Dealing with missing values

In [15]:
#### from pyspark.sql.functions import mean

# Filling missing values with mean
mean_Time = df.select(mean(df['Time'])).collect()
mean_V1 = df.select(mean(df['V1'])).collect()

# Create variables to fill with
mean_Time_val = mean_Time[0][0]
mean_V1_val = mean_V1[0][0]

# Print variables
print(mean_Time_val)
print(mean_V1_val)

88299.5325203252
-2.3261755370132096

In [16]:
# Fill null values
df_uc.na.fill(mean_Time_val, subset=['Time']).select('Time').show()
df_uc.na.fill(mean_V1_val, subset=['V1']).select('V1').show()

+------+
|  Time|
+------+
| 88299|
|146022|
| 58762|
| 40276|
|143438|
| 63470|
|134766|
| 93856|
| 68899|
| 67250|
|  8886|
|171483|
| 76394|
| 80524|
| 55279|
| 25198|
| 91524|
|120591|
|161929|
|129186|
+------+
only showing top 20 rows

+------------+
|          V1|
+------------+
| -0.98432002|
| 0.908636658|
| -0.37396496|
| 1.159373145|
|-5.256433834|
|-1.564204151|
|-1.071284007|
|-6.750508516|
| 0.901017558|
| 1.018612133|
|-2.535852117|
|-10.32558182|
|-0.465170262|
|-0.721462598|
|-5.753851922|
| -15.9036352|
| 1.954851738|
| 1.841628474|
|-0.190794633|
| 0.290155158|
+------------+
only showing top 20 rows

## Combining dataframes

In [17]:
df_comb = df_h1.union(df_h2)

print("df_h1: ", (df_h1.count(), len(df_h1.columns)))
print("df_h2: ", (df_h2.count(), len(df_h2.columns)))
print("df_comb: ", (df_comb.count(), len(df_comb.columns)))

df_h1:  (571, 32)
df_h2:  (485, 32)
df_comb:  (1056, 32)

## Sorting a column

In [18]:
df.select("Amount", "Time", "V1").orderBy(df['Amount'].desc()).show()

+-------+------+------------+
| Amount|  Time|          V1|
+-------+------+------------+
|5026.26|138975|-7.418658885|
| 2693.5|126331|-5.982639392|
|2528.61| 50296|-4.295369193|
|2125.87|122608|-2.003459531|
|1809.68|  9064|-3.499107537|
|1563.24|134021| -2.87553428|
|1504.93|154278|-1.600211299|
|1402.16| 62467|-5.344665375|
|1389.56| 59011| -2.32692237|
|1354.25| 65385|-2.923826664|
| 1335.0|133184|-1.212681701|
|1218.89| 18088|-12.22402062|
|1096.99|154309|-0.082983465|
| 996.27|147501|-1.611877338|
| 966.91|125511| 0.341343499|
| 925.31|134769|-0.967767137|
| 829.41| 87883|-1.360292634|
| 824.83| 70536|-2.271754537|
|  810.0| 34681| -0.23108011|
| 802.52| 41743|-2.144411474|
+-------+------+------------+
only showing top 20 rows

## Feature selecition

In [19]:
# Import VectorAssembler and Vectors
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler

In [20]:
# The input columns are the feature column names, and the output column is what you'd like the new column to be named. 
assembler = VectorAssembler(
    inputCols=['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
               'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
               'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
               'V28', 'Amount', 'Class'],
    outputCol="features")

In [21]:
# Now that we've created the assembler variable, let's actually transform the data.
output = assembler.transform(df)

In [22]:
# Using print schema, you see that the features output column has been added. 
output.printSchema()

# You can see that the features column is a dense vector that combines the various features as expected.
output.head(1)

root
 |-- _c0: integer (nullable = true)
 |-- Time: integer (nullable = true)
 |-- V1: double (nullable = true)
 |-- V2: double (nullable = true)
 |-- V3: double (nullable = true)
 |-- V4: double (nullable = true)
 |-- V5: double (nullable = true)
 |-- V6: double (nullable = true)
 |-- V7: double (nullable = true)
 |-- V8: double (nullable = true)
 |-- V9: double (nullable = true)
 |-- V10: double (nullable = true)
 |-- V11: double (nullable = true)
 |-- V12: double (nullable = true)
 |-- V13: double (nullable = true)
 |-- V14: double (nullable = true)
 |-- V15: double (nullable = true)
 |-- V16: double (nullable = true)
 |-- V17: double (nullable = true)
 |-- V18: double (nullable = true)
 |-- V19: double (nullable = true)
 |-- V20: double (nullable = true)
 |-- V21: double (nullable = true)
 |-- V22: double (nullable = true)
 |-- V23: double (nullable = true)
 |-- V24: double (nullable = true)
 |-- V25: double (nullable = true)
 |-- V26: double (nullable = true)
 |-- V27: double (nullable = true)
 |-- V28: double (nullable = true)
 |-- Amount: double (nullable = true)
 |-- Class: integer (nullable = true)
 |-- features: vector (nullable = true)

[Row(_c0=192463, Time=129707, V1=-0.98432002, V2=0.809110442, V3=1.313431834, V4=0.378640098, V5=1.077080777, V6=0.102875633, V7=1.223544978, V8=-0.064319527, V9=-1.811779644, V10=-0.095408155, V11=-1.177043196, V12=-0.203626696, V13=1.139408969, V14=-0.361021109, V15=-1.274237257, V16=0.967896107, V17=-0.769116363, V18=-0.762870643, V19=-1.50974795, V20=0.209450417, V21=0.258492675, V22=0.522263091, V23=-0.347560932, V24=0.762405289, V25=0.701891989, V26=2.495761332, V27=-0.220928833, V28=0.024871946, Amount=76.87, Class=0, features=DenseVector([129707.0, -0.9843, 0.8091, 1.3134, 0.3786, 1.0771, 0.1029, 1.2235, -0.0643, -1.8118, -0.0954, -1.177, -0.2036, 1.1394, -0.361, -1.2742, 0.9679, -0.7691, -0.7629, -1.5097, 0.2095, 0.2585, 0.5223, -0.3476, 0.7624, 0.7019, 2.4958, -0.2209, 0.0249, 76.87, 0.0]))]

In [23]:
# Let's select two columns (the feature and predictor).
# This is now in the appropriate format to be processed by Spark.
final_data = output.select("features",'Class')
final_data.show()

+--------------------+-----+
|            features|Class|
+--------------------+-----+
|[129707.0,-0.9843...|    0|
|[146022.0,0.90863...|    1|
|[58762.0,-0.37396...|    0|
|[40276.0,1.159373...|    1|
|[143438.0,-5.2564...|    1|
|[63470.0,-1.56420...|    0|
|[134766.0,-1.0712...|    0|
|[93856.0,-6.75050...|    1|
|[68899.0,0.901017...|    0|
|[67250.0,1.018612...|    0|
|[8886.0,-2.535852...|    1|
|[171483.0,-10.325...|    0|
|[76394.0,-0.46517...|    0|
|[80524.0,-0.72146...|    0|
|[55279.0,-5.75385...|    1|
|[25198.0,-15.9036...|    1|
|[91524.0,1.954851...|    1|
|[120591.0,1.84162...|    0|
|[161929.0,-0.1907...|    0|
|[129186.0,0.29015...|    1|
+--------------------+-----+
only showing top 20 rows

In [24]:
from pyspark.ml.feature import ChiSqSelector
from pyspark.ml.linalg import Vectors


selector = ChiSqSelector(numTopFeatures=10, featuresCol="features",
                         outputCol="selectedFeatures", labelCol="Class")

result = selector.fit(final_data).transform(final_data)

print("ChiSqSelector output with top %d features selected" % selector.getNumTopFeatures())
result.show()

ChiSqSelector output with top 10 features selected
+--------------------+-----+--------------------+
|            features|Class|    selectedFeatures|
+--------------------+-----+--------------------+
|[129707.0,-0.9843...|    0|[129707.0,-0.9843...|
|[146022.0,0.90863...|    1|[146022.0,0.90863...|
|[58762.0,-0.37396...|    0|[58762.0,-0.37396...|
|[40276.0,1.159373...|    1|[40276.0,1.159373...|
|[143438.0,-5.2564...|    1|[143438.0,-5.2564...|
|[63470.0,-1.56420...|    0|[63470.0,-1.56420...|
|[134766.0,-1.0712...|    0|[134766.0,-1.0712...|
|[93856.0,-6.75050...|    1|[93856.0,-6.75050...|
|[68899.0,0.901017...|    0|[68899.0,0.901017...|
|[67250.0,1.018612...|    0|[67250.0,1.018612...|
|[8886.0,-2.535852...|    1|[8886.0,-2.535852...|
|[171483.0,-10.325...|    0|[171483.0,-10.325...|
|[76394.0,-0.46517...|    0|[76394.0,-0.46517...|
|[80524.0,-0.72146...|    0|[80524.0,-0.72146...|
|[55279.0,-5.75385...|    1|[55279.0,-5.75385...|
|[25198.0,-15.9036...|    1|[25198.0,-15.9036...|
|[91524.0,1.954851...|    1|[91524.0,1.954851...|
|[120591.0,1.84162...|    0|[120591.0,1.84162...|
|[161929.0,-0.1907...|    0|[161929.0,-0.1907...|
|[129186.0,0.29015...|    1|[129186.0,0.29015...|
+--------------------+-----+--------------------+
only showing top 20 rows

## Dealing with imbalances - undersampling

In [25]:
from pyspark.sql.functions import col, explode, array, lit

major_df = df.filter(col("Class") == 0)
minor_df = df.filter(col("Class") == 1)
ratio = int(major_df.count()/minor_df.count())
print("ratio: {}".format(ratio))

# We can see that the ratio is 1 i.e. not imbalanced, since the dataset has already been rebalanced

ratio: 1

In [26]:
sampled_majority_df = major_df.sample(False, 1/ratio)
combined_df_2 = sampled_majority_df.unionAll(minor_df)
combined_df_2.show()

+------+------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------+-----+
|   _c0|  Time|          V1|          V2|          V3|          V4|          V5|          V6|          V7|          V8|          V9|         V10|         V11|         V12|         V13|         V14|         V15|         V16|         V17|         V18|         V19|         V20|         V21|         V22|         V23|         V24|         V25|         V26|         V27|         V28|Amount|Class|
+------+------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------+-----+
|192463|129707| -0.98432002| 0.809110442| 1.313431834| 0.378640098| 1.077080777| 0.102875633| 1.223544978|-0.064319527|-1.811779644|-0.095408155|-1.177043196|-0.203626696| 1.139408969|-0.361021109|-1.274237257| 0.967896107|-0.769116363|-0.762870643| -1.50974795| 0.209450417| 0.258492675| 0.522263091|-0.347560932| 0.762405289| 0.701891989| 2.495761332|-0.220928833| 0.024871946| 76.87|    0|
| 81029| 58762| -0.37396496| 0.361634234| 2.373561685| 0.310673143|-0.784006572| 0.067550533|-0.150632181|  0.35961421| 0.581845802|-0.671433143|-0.639201339|-0.501323593|-1.657929341|-0.164314213| 0.386335749|-0.240619301| 0.324554916|-0.433876741|-0.371161195|  -0.1827964|  0.01287912| 0.144327718|-0.005737447| 0.397914752|-0.347845341| 0.291212807| 0.047656917| 0.029172957|  11.5|    0|
| 91434| 63470|-1.564204151| 0.253239307| 0.374165856| 1.539532838| 0.423781088|-0.361605454| 0.760453237|-0.002482775|-0.399411718| 0.246366217|-0.359712093| 0.756451751| 1.097324252| 0.035751892| 0.443588871|-1.106788306| 0.444530516|-0.720026619| 0.585020668|-0.047857274| 0.064446289| 0.759082482| 0.220749719| 0.151762315|-0.380927136|-0.272589436| 0.035805694|-0.023251332|100.92|    0|
|203325|134766|-1.071284007| 0.893980685|-1.393912233| 1.184488127| 2.223117603|-0.782882472| 0.624152042|  0.29438033|-0.885704372|-0.815912073| -1.34101878|-0.112226306| 0.489160182|-0.818323869| -0.13212714|-0.404984078| 1.228495069|  0.54626077| 0.788297771|  0.33787218| 0.108440952| 0.205780786|-0.347580019|-0.062431561| 0.169319283|-0.373892353| 0.351176615| 0.066051808|   1.0|    0|
|104068| 68899| 0.901017558|-0.995418568| 0.872056381| 0.192595669|-1.133904292| 0.327022735|-0.729865916| 0.115515109| 1.129340519|-0.382607564|-1.407100907| 0.190575173|  0.78280387|-0.616484549| 0.952842468| 0.875306801|-0.728157813| 0.445420107|  0.10645349| 0.392483353| 0.211844313| 0.370527451|-0.319429291| -0.45608877|   0.1986918| 1.185880459|-0.050280318| 0.046316924| 198.0|    0|
| 99719| 67250| 1.018612133|-0.272599136|  1.22497329| 1.141354061|-0.661930036| 1.038439295|-0.900784193| 0.586134199| 0.809710033|-0.086390548| 1.151002944| 0.691494275|-1.320454045| 0.139204598| 0.119345294| -0.25855114| 0.134348916|-0.322023926|-0.638152651|-0.262527705| 0.032206073|  0.26926773| 0.057014685|-0.310005271| 0.195169346|-0.363445554| 0.093506611| 0.019010354| 10.96|    0|
|283268|171483|-10.32558182| -10.2567549|-1.920519963| 4.742631234| 6.596055138|-4.144105747|-5.947807176|-1.959710084| 1.884899731| 1.122660904| 1.031897641|  1.71689088| 0.471279054|-0.978094536| 0.708468212|-0.419409917| 1.972062806| 0.622804031| 3.558426917|-4.806939889| 0.311710291|-0.286814786|-8.451590538|  1.64407629|-1.927759906| 0.382244344| 3.800539534|-4.555242788|  3.69|    0|
|121986| 76394|-0.465170262| 0.898783954| 0.915132707| 0.363621079|  0.60750033|-0.352138123|  0.94473379|-0.196290544|-0.556754401| -0.33793507|-1.156284886| 0.004748458| 0.842441172| 0.040825044| 0.709302475|  0.17163956| -0.77197426|  0.19490569| 0.082029383| 0.004530366| 0.075238444| 0.189574494| -0.29505654|-0.429240538| 0.390885303|-0.331294211|-0.093395424|  0.04454786| 46.86|    0|
|133770| 80524|-0.721462598| 1.275847321| 0.733151954|-0.177397828| 0.143047975|-0.490873481|  0.44336971| 0.283726447|-0.615486314|-0.609275422|-1.353346566|-0.148731985| 0.296722223| 0.439631754| 0.708930431| 0.431922281|-0.501992031|-0.031795579| 0.383941557|-0.143764681|-0.084945559|-0.445386201|-0.091120439|-0.454858932|-0.305009245| 0.129199679|-0.171579169| 0.065233162|  5.49|    0|
|171329|120591| 1.841628474| 0.158025248| 0.206360477| 3.619911473| 0.001836937| 0.977849663|-0.633992558| 0.178328936|-0.284816778| 1.309424224|-2.006508259| 0.135660496|  1.61322282|-0.634469303|-0.203931016| 1.796590529|-1.543583296| 0.299049012|-1.465553273|-0.074649082| 0.028859173| 0.110193819| 0.156403594|-1.026893869|-0.362463499|-0.114276779|  0.03193662|-0.020752404| 45.58|    0|
|265543|161929|-0.190794633| 0.762668226|-1.763566849|-1.562175672| 3.141495695| 3.195015274| 0.336650802| 0.843347743|-0.018443516|-0.578055165| 0.155116639|-0.158480804|-0.418650562|-0.828362592| 0.177133917| 0.196437676| 0.334734907|-0.390357635|-0.382503491|-0.021027681| -0.31405465|-0.896446761| 0.204102291| 0.590985574|-0.425549927| 0.143025666|-0.004437083| 0.050620355|  2.28|    0|
|145193| 86707|-3.576291703|  3.55340723|-1.571126415|-1.692567796| -0.04789507|  -0.7715076| 0.800001502| 0.117819135| 2.735133939| 4.677648974| 0.759662632| 0.962694648| 0.289925236|-0.906818301|-0.856283508|-0.101967046|-0.994444987|-0.390761886|-0.099474989|  2.04012337|-0.725246715|-0.873301768| 0.189135379|-0.556543527| 0.386678897| 0.221154123| 1.880012729| 1.174951041|  8.93|    0|
|133700| 80493| 1.282516072| 0.322631165|-0.411510024| 0.844479178| 0.292183698|-0.512588539| 0.328938172|-0.076668589|-0.257511367| 0.260988888| 0.458668463|-0.143236606|-1.511977418| 1.026362271| 0.201133067| 0.252261244| -0.72508367| 0.538655677|  0.30628665|-0.221959182|-0.008673043|-0.073676427|-0.223652382|-0.378384515| 0.862310551|-0.266005953|-0.022629643|-0.009613143|   1.0|    0|
|191146|129134| 0.338302422| 0.203129068|-1.187675957|-1.690692704|  0.00176199|-0.344074309|-0.180149339| 0.374200514|-0.781184123|-0.532933673|-1.375545791|-1.039553096| 0.222498512|-1.402072616| -0.33801916| 1.708641722| 0.959232118| -0.59670254| 0.307388261|-0.005517911| 0.221609196| 0.450144847| 0.201134631|-0.079174133|-0.698723925|-0.356012053|  -0.0599706|-0.018838014| 49.95|    0|
| 67410| 52521| 1.009505997|-0.215303552| 2.239280736| 3.016949631|-1.190015495| 1.444945748|-1.315813767| 0.586344919|  1.13628542| 0.193699925|-1.416474322| 0.635467408|-0.002253543|-1.281586975|-1.667012253| -0.18758709| 0.357145997|-0.549829288|-0.903548778|-0.210806962| 0.089266633| 0.790814607|-0.082397006| 0.145507709| 0.404252206| 0.279747011|  0.11221827| 0.035986422|   0.0|    0|
|239574|150167|-1.347743702| 0.821241495| -1.59318328|-0.250396578| 3.768887697| 3.510499627| 1.081563956|  0.18271935| 0.220964827| 1.573934001|-0.087084035|-0.283478597|-0.471651518|-0.044851275| 0.245465501|-1.426966712|-0.224338953|-0.537211129|  0.71546496| 0.151654813|-0.111621935| 0.532129553|-0.239438829| 0.726286683| 0.128644608|   -0.442189|-0.176010664| 0.120953619|  32.0|    0|
|247727|153671|-1.135103452| 2.290090807|-1.550147695| 3.757446403| 1.345115125| 1.020978393| 1.456980879|-0.027058309|-1.431469487| 3.866303042| 0.006762128|-0.619870802|-0.145209702| 0.525571768| 0.040446582|-0.225123342| -0.48136107| 0.526830039| 1.532964184| 0.650846828|-0.092962672| 0.771398249| 0.102097885|-0.211532583|  -0.8160753| 0.304606333| 0.711857571| 0.155014753| 92.26|    0|
|  2535|  2098|-0.445649191| 0.462052728|  1.05035912|-2.180047959| 0.231164713|-0.758195479|  0.85140294| -0.03863857| 0.886612832|-0.963636708| 1.220729946|-0.113401662|-2.409582146| 0.720245667| 0.664383761| -0.57846833|-0.424141391| 0.345752394|-0.155282632|-0.124338917| 0.115611971| 0.610117864|-0.254143845|-0.033585347|-0.100171312| -0.82006841| 0.237875431|-0.031778691|   1.0|    0|
|174967|122150|  1.83093081| 0.176010404|-0.003442673| 3.773642047| -0.02700487| 0.693592245|-0.500444818| 0.184983987| -0.29587119| 1.359520247|-1.531043011|-0.290901143| 0.102727129|-0.257470109|-0.562230322| 1.212489757|-0.962968828| 0.125022842|-1.695800127|-0.190525778| 0.210540183| 0.626289909| 0.150695079| 0.646376373|-0.154398015|  0.04144559| 0.002165294|-0.022085778| 35.23|    0|
|260326|159502| 1.883172792|-0.465819966|-0.573023188| 0.019093097|-0.350039047|-0.250323589|-0.349144488|-0.092381455| 0.994424963|-0.261244003|-0.509015309|  1.18750723| 1.686994702| -0.27064568| 0.951040537| 0.299786931|-0.712752428|-0.354280815|-0.124117193| 0.060680702| -0.10079946|-0.300306011| 0.335043544| 0.617792194|-0.473910021|-0.312664272| 0.001591762|-0.014800995| 76.24|    0|
+------+------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------+-----+
only showing top 20 rows

## Statistical transformation

In [27]:
from pyspark.sql.functions import col
from pyspark.sql.functions import log

df_demonstration = df.select("Amount")
df_log = df_demonstration.withColumn("logvalue", log10(col("Amount")))
df_log.show()

+------+-------------------+
|Amount|           logvalue|
+------+-------------------+
| 76.87| 1.8857568810692675|
|  1.18|0.07188200730612536|
|  11.5| 1.0606978403536116|
|   1.0|                0.0|
|   8.9| 0.9493900066449128|
|100.92|  2.003977241845537|
|   1.0|                0.0|
|209.65|  2.321494866739587|
| 198.0|  2.296665190261531|
| 10.96| 1.0398105541483504|
|   1.0|                0.0|
|  3.69| 0.5670263661590603|
| 46.86|  1.670802284260944|
|  5.49| 0.7395723444500919|
|   1.0|                0.0|
| 99.99| 1.9999565683801925|
|   1.0|                0.0|
| 45.58| 1.6587743208443568|
|  2.28|0.35793484700045375|
|  7.18| 0.8561244442423003|
+------+-------------------+
only showing top 20 rows

## Regression

In [28]:
from pyspark.ml.classification import LogisticRegression
from pyspark.ml import Pipeline

In [29]:
df = df.withColumnRenamed("Class","label")

# Print data schema.
df.printSchema()

# Print data columns.
df.columns

root
 |-- _c0: integer (nullable = true)
 |-- Time: integer (nullable = true)
 |-- V1: double (nullable = true)
 |-- V2: double (nullable = true)
 |-- V3: double (nullable = true)
 |-- V4: double (nullable = true)
 |-- V5: double (nullable = true)
 |-- V6: double (nullable = true)
 |-- V7: double (nullable = true)
 |-- V8: double (nullable = true)
 |-- V9: double (nullable = true)
 |-- V10: double (nullable = true)
 |-- V11: double (nullable = true)
 |-- V12: double (nullable = true)
 |-- V13: double (nullable = true)
 |-- V14: double (nullable = true)
 |-- V15: double (nullable = true)
 |-- V16: double (nullable = true)
 |-- V17: double (nullable = true)
 |-- V18: double (nullable = true)
 |-- V19: double (nullable = true)
 |-- V20: double (nullable = true)
 |-- V21: double (nullable = true)
 |-- V22: double (nullable = true)
 |-- V23: double (nullable = true)
 |-- V24: double (nullable = true)
 |-- V25: double (nullable = true)
 |-- V26: double (nullable = true)
 |-- V27: double (nullable = true)
 |-- V28: double (nullable = true)
 |-- Amount: double (nullable = true)
 |-- label: integer (nullable = true)

['_c0',
 'Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount',
 'label']

In [30]:
my_cols = df.select(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
               'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
               'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
               'V28', 'Amount', 'label'])

In [31]:
# Remove NA values
my_final_data = my_cols.na.drop()

In [32]:
df.columns

['_c0',
 'Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount',
 'label']

In [33]:
from pyspark.ml.feature import (VectorAssembler,VectorIndexer,
                                OneHotEncoder,StringIndexer)

In [34]:
# Now we can assemble all of this as one vector in the features column. 
assembler = VectorAssembler(inputCols=['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
               'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
               'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
               'V28', 'Amount'],outputCol='features')

In [35]:
from pyspark.ml.classification import LogisticRegression
from pyspark.ml import Pipeline

# Train/test split (80/20 split chosen)
data_train, data_test = my_final_data.randomSplit([0.8,0.2])

In [36]:
log_reg = LogisticRegression(featuresCol='features',labelCol='label')

In [37]:
# Lists everything we want to do. Index data, encode data, assemble data and then pass in the actual model.
pipeline = Pipeline(stages=[assembler,log_reg])

In [38]:
# Hyper parameter tuning
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder

paramGrid = ParamGridBuilder() \
    .addGrid(log_reg.aggregationDepth,[2,5,10])\
    .addGrid(log_reg.elasticNetParam,[0.0, 0.5, 1.0])\
    .addGrid(log_reg.fitIntercept,[False, True])\
    .addGrid(log_reg.maxIter,[10, 100, 1000])\
    .addGrid(log_reg.regParam,[0.01, 0.5, 2.0]) \
    .build()

In [39]:
from pyspark.ml.evaluation import BinaryClassificationEvaluator

crossval = CrossValidator(estimator=pipeline,
                          estimatorParamMaps=paramGrid,
                          evaluator=BinaryClassificationEvaluator(),
                          numFolds=2,
                         ) 

# Run cross-validation, and choose the best set of parameters.
cvModel = crossval.fit(data_train)

In [40]:
# Note pipeline. Call it as you would call a machine learning object.
prediction = cvModel.transform(data_train)

In [41]:
# Evaluate the model using the binary classifer.
from pyspark.ml.evaluation import BinaryClassificationEvaluator

my_eval = BinaryClassificationEvaluator(rawPredictionCol='prediction',
                                       labelCol='label')

In [42]:
prediction.select('label','prediction').show()

+-----+----------+
|label|prediction|
+-----+----------+
|    0|       0.0|
|    1|       1.0|
|    1|       1.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    0|       0.0|
|    1|       1.0|
|    0|       1.0|
|    1|       1.0|
|    1|       1.0|
|    1|       1.0|
|    1|       1.0|
+-----+----------+
only showing top 20 rows

In [43]:
AUC = my_eval.evaluate(prediction)

AUC

0.9434122253535178

In [44]:
# Let's start off with binary classification.
from pyspark.ml.evaluation import BinaryClassificationEvaluator

# Note that the label column isn't named label, it's named PrivateIndex in this case.
my_binary_eval1 = BinaryClassificationEvaluator(labelCol = 'label')

In [45]:
sumModel = cvModel.bestModel.stages[-1]

In [46]:
print("Coefficients: " + str(sumModel.coefficients) + "\n")
print("Intercept: " + str(sumModel.intercept))

Coefficients: [0.0,-0.01575735836320621,0.0,-0.02862765968368443,0.4464185027414538,0.0,-0.255975237693972,0.0,-0.0394912488614178,0.0,-0.13056737959609294,0.198612924846988,-0.2350708179242306,-0.1297143145854754,-0.37847780773504003,-0.03474611021826392,-0.07194334002085218,0.0,0.0,0.0,-0.007199255421488341,0.030275518624218952,0.0032234454456543838,-0.05845346873321611,0.0,0.0,-0.06370411378510321,0.0,0.6187912448310326,0.0011296313794410884]

Intercept: -2.395357795449395

In [47]:
print ('Best Param (regParam): ', sumModel._java_obj.getRegParam())

print('Best Param (MaxIter): ', sumModel._java_obj.getMaxIter())

print('Best Param (elasticNetParam): ', sumModel._java_obj.getElasticNetParam())

Best Param (regParam):  0.01
Best Param (MaxIter):  100
Best Param (elasticNetParam):  0.5

## Trialing other ML algorithms

In [48]:
assembler1 = VectorAssembler(inputCols=['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
               'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
               'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
               'V28', 'Amount'],outputCol='features')

In [49]:
output = assembler1.transform(df)
df.columns

['_c0',
 'Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount',
 'label']

In [50]:
from pyspark.ml.feature import StringIndexer
indexer = StringIndexer(inputCol="label", outputCol="labelIndex")
output_fixed = indexer.fit(output).transform(output)

In [51]:
final_data = output_fixed.select("features",'labelIndex')

In [52]:
train_data,test_data = final_data.randomSplit([0.8,0.2])

In [53]:
from pyspark.ml.classification import DecisionTreeClassifier,GBTClassifier,RandomForestClassifier
from pyspark.ml import Pipeline

In [59]:
# Create models
dt = DecisionTreeClassifier(labelCol='labelIndex',featuresCol='features')
rf = RandomForestClassifier(labelCol='labelIndex',featuresCol='features')
gb = GBTClassifier(labelCol='labelIndex',featuresCol='features')

In [60]:
# Train models
dt_model = dt.fit(train_data)
rf_model = rf.fit(train_data)
gb_model = gb.fit(train_data)

In [61]:
# Test models
dt_predictions = dt_model.transform(test_data)
rf_predictions = rf_model.transform(test_data)
gb_predictions = gb_model.transform(test_data)

In [62]:
# Evaluate models
# Let's start off with binary classification.
from pyspark.ml.evaluation import BinaryClassificationEvaluator

# Note that the label column isn't named label, it's named PrivateIndex in this case.
my_binary_eval = BinaryClassificationEvaluator(labelCol = 'labelIndex')

In [64]:
print("Decision tree AUC ROC")
print(my_binary_eval.evaluate(dt_predictions))

print("Random forest AUC ROC")
print(my_binary_eval.evaluate(rf_predictions))

my_binary_gbt_eval = BinaryClassificationEvaluator(labelCol='labelIndex', rawPredictionCol='prediction')
print("Gradient boosted AUC ROC")
print(my_binary_gbt_eval.evaluate(gb_predictions))

Decision tree AUC ROC
0.9297531512605042
Random forest AUC ROC
0.9842436974789917
Gradient boosted AUC ROC
0.9455532212885153

In [65]:
# Let's import the evaluator.
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

In [66]:
# Select (prediction, true label) and compute test error. 
acc_evaluator = MulticlassClassificationEvaluator(labelCol="labelIndex", predictionCol="prediction", metricName="accuracy")

In [68]:
dt_acc = acc_evaluator.evaluate(dt_predictions)
rf_acc = acc_evaluator.evaluate(rf_predictions)
gb_acc = acc_evaluator.evaluate(gb_predictions)

In [69]:
print('A decision tree model has an accuracy of: {0:2.2f}%'.format(dt_acc*100))
print('-'*40)
print('A random forest model has an accuracy of: {0:2.2f}%'.format(rf_acc*100))
print('-'*40)
print('An GBT model has an accuracy of: {0:2.2f}%'.format(gb_acc*100))

A decision tree model has an accuracy of: 93.46%
----------------------------------------
A random forest model has an accuracy of: 94.86%
----------------------------------------
An GBT model has an accuracy of: 94.39%

In [73]:
feature_importances_dt = dt_model.featureImportances
print(type(feature_importances_dt))

<class 'pyspark.ml.linalg.SparseVector'>

In [88]:
from  pyspark.mllib.linalg import SparseVector
import pandas as pd

col_n = ['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
               'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
               'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
               'V28', 'Amount']

df_dt = pd.DataFrame(feature_importances_dt.toArray())
df_dt["Features"] = col_n
df_dt

           0 Features
0   0.004275     Time
1   0.000000       V1
2   0.000000       V2
3   0.000000       V3
4   0.041457       V4
5   0.000000       V5
6   0.019692       V6
7   0.006042       V7
8   0.020218       V8
9   0.009772       V9
10  0.015283      V10
11  0.000000      V11
12  0.028149      V12
13  0.011599      V13
14  0.781922      V14
15  0.007775      V15
16  0.000000      V16
17  0.000000      V17
18  0.000000      V18
19  0.000000      V19
20  0.014739      V20
21  0.007696      V21
22  0.015835      V22
23  0.000000      V23
24  0.000000      V24
25  0.000000      V25
26  0.000000      V26
27  0.000000      V27
28  0.015547      V28
29  0.000000   Amount

In [89]:
feature_importances_rf = rf_model.featureImportances
df_rf = pd.DataFrame(feature_importances_rf.toArray())
df_rf["Features"] = col_n
df_rf

           0 Features
0   0.001302     Time
1   0.003013       V1
2   0.017686       V2
3   0.047178       V3
4   0.138585       V4
5   0.021478       V5
6   0.010456       V6
7   0.068081       V7
8   0.003620       V8
9   0.002965       V9
10  0.079469      V10
11  0.039801      V11
12  0.011024      V12
13  0.003898      V13
14  0.388362      V14
15  0.001248      V15
16  0.017282      V16
17  0.068170      V17
18  0.020407      V18
19  0.005119      V19
20  0.007968      V20
21  0.006795      V21
22  0.004286      V22
23  0.004948      V23
24  0.002720      V24
25  0.003810      V25
26  0.004680      V26
27  0.004219      V27
28  0.006271      V28
29  0.005160   Amount

In [97]:
feature_importances_gb = rf_model.featureImportances
df_gb = pd.DataFrame(feature_importances_gb.toArray())
df_gb["Features"] = col_n
df_gb

           0 Features
0   0.001302     Time
1   0.003013       V1
2   0.017686       V2
3   0.047178       V3
4   0.138585       V4
5   0.021478       V5
6   0.010456       V6
7   0.068081       V7
8   0.003620       V8
9   0.002965       V9
10  0.079469      V10
11  0.039801      V11
12  0.011024      V12
13  0.003898      V13
14  0.388362      V14
15  0.001248      V15
16  0.017282      V16
17  0.068170      V17
18  0.020407      V18
19  0.005119      V19
20  0.007968      V20
21  0.006795      V21
22  0.004286      V22
23  0.004948      V23
24  0.002720      V24
25  0.003810      V25
26  0.004680      V26
27  0.004219      V27
28  0.006271      V28
29  0.005160   Amount